/* ==========================================================================
   PuzzleStudio — js/games/e15_measuring.js            ENGINE 15 · Measuring
   --------------------------------------------------------------------------
   Self-contained: logic + 3 skins + its own CSS. No DOM access until mount().

   THE PUZZLE
     The decanting problem, played straight. You have vessels of awkward,
     deliberately unhelpful capacities and you need an exact volume that is
     not written on any of them. Three operations and nothing else:

       FILL   a vessel to the brim from the source
       EMPTY  a vessel onto the ground
       POUR   one vessel into another until the source runs out or the
              destination is full — whichever happens first

     Everything is generated by BFS over the full state graph, so the target
     is provably reachable and the optimal move count is known exactly. You
     are scored against that number, not against a guess.

   THE ESCALATION
     Low tiers: two vessels and a tap you can use forever.
     Tier 3:    a third vessel, so the state space stops being a straight line.
     Tier 4+:   the tap is gone. What is already in the vessels is all there
                is, FILL and EMPTY do not exist, and you can only pour between
                them. That is a genuinely different and much nastier puzzle.

   THE ROOM (arena)
     The vessels are objects standing on the floor of a room, not widgets in a
     row. You pick one up, you carry it to the tap to fill it, to the drain to
     tip it out, or to another vessel to pour. Every move in the BFS is a walk
     across the room with something heavy in your hands, which is what the jug
     problem always was. The bench at the end of the room is the station: it
     keeps the count, the take-backs and, once it is measured, the choice.

   THE BRANCH
     Having measured it out, you either stay and draw off everything you can
     carry, or you take the one exact measure and move while you still can.
   ========================================================================== */
(function (root) {
  'use strict';

  var PS = root.PuzzleStudio;
  if (!PS || !PS.registry) { if (root.console) console.error('[e15] core not loaded'); return; }

  /* ======================================================== SKIN CONTENT == */

  var CONTENT = {
    fuel_mix: {
      unit: 'L',
      source: 'the bowser',
      sourceIcon: '\u26FD',
      drain: 'the floor drain',
      drainIcon: '\uD83D\uDD73\uFE0F',
      vessels: ['Drum', 'Jerrycan', 'Measure'],
      icons: ['\uD83D\uDEE2\uFE0F', '\u26FD', '\uD83E\uDD5B'],
      substance: 'mix',
      goal: 'The pump will not start on anything but a clean %T% litre charge.',
      sealed: 'The bowser ran dry an hour ago. What is standing in these cans is every drop on site.',
      fillVerb: 'Fill', emptyVerb: 'Tip out',
      fillLine: 'Fuel glugs in until it kisses the rim.',
      emptyLine: 'It goes over the concrete and runs for the drain.',
      pourLine: 'You hold both cans steady and let it cross.',
      solve: 'Exactly %T% litres, dead level with the mark.',
      failLine: 'You lose the thread of it and end up with a yard full of fuel.',
      item: 'fuel', bonus: 'canister',
      relief: { light: 10 },
      stay: { icon: '\uD83D\uDEE2\uFE0F', title: 'Draw off everything left', desc: 'Another twenty minutes and every empty can on the rack goes with you.' },
      go:   { icon: '\uD83C\uDFC3', title: 'Take the charge and run it over', desc: 'One measure, both hands, and the generator shed before dark.' }
    },
    antidote: {
      unit: 'ml',
      source: 'the saline drum',
      sourceIcon: '\uD83D\uDCA7',
      drain: 'the sluice',
      drainIcon: '\uD83D\uDD73\uFE0F',
      vessels: ['Flask', 'Beaker', 'Vial'],
      icons: ['\u2697\uFE0F', '\uD83E\uDDEA', '\uD83D\uDC8A'],
      substance: 'dilution',
      goal: 'The chart is very clear: %T% millilitres. More is a second poisoning.',
      sealed: 'The drum is empty and the taps are dead. Three vessels, and whatever is already in them.',
      fillVerb: 'Charge', emptyVerb: 'Discard',
      fillLine: 'You charge it to the brim and let the meniscus settle.',
      emptyLine: 'Down the sluice. You cannot afford to guess with it.',
      pourLine: 'A slow, careful transfer, no splash.',
      solve: 'Exactly %T% millilitres, sitting flat on the line.',
      failLine: 'You lose count somewhere in the middle and dare not use any of it.',
      item: 'medkit', bonus: 'bandage',
      relief: { health: 10 },
      stay: { icon: '\uD83E\uDE79', title: 'Mix a second dose', desc: 'There is enough for one more if you are quick, and there is always one more.' },
      go:   { icon: '\uD83C\uDFC3', title: 'Get the dose down the hall', desc: 'It is measured. Standing here admiring it does nothing for anybody.' }
    },
    ration: {
      unit: 'L',
      source: 'the melt tank',
      sourceIcon: '\uD83D\uDCA7',
      drain: 'the snow outside',
      drainIcon: '\u2744\uFE0F',
      vessels: ['Billy', 'Canteen', 'Cup'],
      icons: ['\uD83E\uDEA3', '\uD83C\uDF76', '\u2615'],
      substance: 'water',
      goal: 'Split it honestly or do not split it at all: %T% litres, exactly.',
      sealed: 'The tank is down to sludge. What the three of you are holding is the whole ration.',
      fillVerb: 'Draw', emptyVerb: 'Pour out',
      fillLine: 'You draw it off until the billy will not take any more.',
      emptyLine: 'It hits the snow and steams. That hurts to watch.',
      pourLine: 'Steady hands, no spill, the way you were taught.',
      solve: 'Exactly %T% litres, level with the rim.',
      failLine: 'Half of it is in the snow and nobody trusts the count now.',
      item: 'water', bonus: 'ration',
      relief: { energy: 12 },
      stay: { icon: '\uD83E\uDEA3', title: 'Fill everything you can carry', desc: 'Weight now against thirst later. It is not a close argument.' },
      go:   { icon: '\uD83C\uDFC3', title: 'Move while there is light', desc: 'You have the measure. Water you cannot carry is water for somebody else.' }
    }
  };

  var LETTERS = ['A', 'B', 'C', 'D'];

  /* ============================================================== SOLVER == */
  /* The whole engine rests on this: encode every possible combination of
     levels as an integer, walk the graph, and never serve a target that the
     search has not actually reached. */

  function Space(caps, sealed) {
    this.caps = caps;
    this.sealed = sealed;
    this.n = caps.length;
    this.mult = [];
    var total = 1;
    for (var i = 0; i < this.n; i++) { this.mult.push(total); total *= caps[i] + 1; }
    this.total = total;
  }

  Space.prototype.encode = function (a) {
    var v = 0;
    for (var i = 0; i < this.n; i++) v += a[i] * this.mult[i];
    return v;
  };

  Space.prototype.decode = function (code) {
    var a = [];
    for (var i = 0; i < this.n; i++) a.push(Math.floor(code / this.mult[i]) % (this.caps[i] + 1));
    return a;
  };

  /** Every legal move out of `code`, as [{ move, to }]. */
  Space.prototype.edges = function (code) {
    var a = this.decode(code), out = [], i, j;
    if (!this.sealed) {
      for (i = 0; i < this.n; i++) {
        if (a[i] < this.caps[i]) out.push({ move: { kind: 'fill', i: i }, to: code + (this.caps[i] - a[i]) * this.mult[i] });
        if (a[i] > 0) out.push({ move: { kind: 'empty', i: i }, to: code - a[i] * this.mult[i] });
      }
    }
    for (i = 0; i < this.n; i++) {
      if (a[i] === 0) continue;
      for (j = 0; j < this.n; j++) {
        if (i === j || a[j] === this.caps[j]) continue;
        var amt = Math.min(a[i], this.caps[j] - a[j]);
        if (amt <= 0) continue;
        out.push({ move: { kind: 'pour', i: i, j: j, amt: amt }, to: code - amt * this.mult[i] + amt * this.mult[j] });
      }
    }
    return out;
  };

  /** Forward BFS from `start`. dist[code] = moves, or -1 if unreachable. */
  Space.prototype.reach = function (start) {
    var dist = new Array(this.total);
    for (var k = 0; k < this.total; k++) dist[k] = -1;
    dist[start] = 0;
    var q = [start], head = 0;
    while (head < q.length) {
      var c = q[head++];
      var e = this.edges(c);
      for (var i = 0; i < e.length; i++) {
        if (dist[e[i].to] !== -1) continue;
        dist[e[i].to] = dist[c] + 1;
        q.push(e[i].to);
      }
    }
    return { dist: dist, order: q };
  };

  /**
   * Reverse BFS: distance from every reachable state TO the nearest goal.
   * This is what powers both the optimal count and the hint, and it means the
   * hint is always a genuinely optimal move rather than a plausible one.
   */
  Space.prototype.toGoal = function (reachOrder, reachDist, isGoal) {
    var self = this;
    var rev = {};
    var d = {};
    var i, j, e;
    for (i = 0; i < reachOrder.length; i++) {
      var c = reachOrder[i];
      e = self.edges(c);
      for (j = 0; j < e.length; j++) {
        if (reachDist[e[j].to] === -1) continue;
        (rev[e[j].to] || (rev[e[j].to] = [])).push(c);
      }
    }
    var q = [], head = 0;
    for (i = 0; i < reachOrder.length; i++) {
      if (isGoal(self.decode(reachOrder[i]))) { d[reachOrder[i]] = 0; q.push(reachOrder[i]); }
    }
    while (head < q.length) {
      var cur = q[head++];
      var back = rev[cur] || [];
      for (j = 0; j < back.length; j++) {
        if (d[back[j]] !== undefined) continue;
        d[back[j]] = d[cur] + 1;
        q.push(back[j]);
      }
    }
    return d;
  };

  /* =============================================================== BUILD == */

  var POOLS = {
    two_easy:   [[5, 3], [7, 4], [8, 5], [7, 3], [6, 4]],
    two_hard:   [[9, 4], [11, 5], [9, 7], [12, 5], [10, 6], [13, 6]],
    three_tap:  [[10, 7, 4], [12, 7, 5], [11, 8, 3], [13, 9, 4], [12, 9, 5]],
    three_seal: [[8, 5, 3], [12, 7, 5], [10, 7, 3], [12, 9, 5], [16, 9, 7], [14, 9, 5]]
  };

  function poolFor(t) {
    if (t <= 1) return { key: 'two_easy', sealed: false, band: [4, 9] };
    if (t === 2) return { key: 'two_hard', sealed: false, band: [6, 13] };
    if (t === 3) return { key: 'three_tap', sealed: false, band: [6, 14] };
    return { key: 'three_seal', sealed: true, band: [6, 20] };
  }

  /** Try one capacity set; return a fully verified puzzle core or null. */
  function attempt(caps, sealed, band, rng) {
    var space = new Space(caps, sealed);
    var startArr = [];
    for (var i = 0; i < caps.length; i++) startArr.push(sealed && i === 0 ? caps[0] : 0);
    var start = space.encode(startArr);

    var r = space.reach(start);
    var biggest = Math.max.apply(null, caps);

    // Every volume that some reachable state actually holds in some vessel.
    var seen = {};
    for (var k = 0; k < r.order.length; k++) {
      var a = space.decode(r.order[k]);
      for (var v = 0; v < a.length; v++) if (a[v] > 0) seen[a[v]] = true;
    }

    var cands = [];
    for (var T = 1; T <= biggest; T++) {
      if (!seen[T]) continue;
      if (caps.indexOf(T) >= 0) continue;                 // "just fill that one" is not a puzzle
      if (sealed && T === startArr[0]) continue;
      var goalPred = (function (target) {
        return function (arr) {
          for (var q = 0; q < arr.length; q++) if (arr[q] === target) return true;
          return false;
        };
      })(T);
      var dg = space.toGoal(r.order, r.dist, goalPred);
      var opt = dg[start];
      if (opt === undefined || opt < 3) continue;

      // NO SOFT-LOCKS. In sealed mode the graph is not automatically strongly
      // connected, so a careless target could strand the player in a corner
      // with the goal permanently out of reach. Only serve targets where EVERY
      // reachable state can still get there.
      var safe = true;
      for (var s = 0; s < r.order.length; s++) {
        if (dg[r.order[s]] === undefined) { safe = false; break; }
      }
      cands.push({ target: T, optimal: opt, safe: safe, distToGoal: dg });
    }
    if (!cands.length) return null;

    var safeOnly = cands.filter(function (c) { return c.safe; });
    if (safeOnly.length) cands = safeOnly;

    var lo = band[0], hi = band[1];
    var mid = (lo + hi) / 2;
    var pickd = rng.weighted(cands, function (c) {
      var inBand = c.optimal >= lo && c.optimal <= hi;
      var closeness = 1 / (1 + Math.abs(c.optimal - mid));
      return (inBand ? 6 : 0.35) * closeness;
    });
    if (!pickd) pickd = cands[cands.length - 1];

    return {
      space: space, caps: caps, sealed: sealed,
      start: start, startArr: startArr,
      target: pickd.target, optimal: pickd.optimal,
      distToGoal: pickd.distToGoal
    };
  }

  function build(state, rng, tier, skin) {
    var C = CONTENT[skin.id] || CONTENT.fuel_mix;
    var t = Math.min(6, Math.max(1, tier));
    var spec = poolFor(t);

    var core = null;
    var order = rng.shuffle(POOLS[spec.key]);
    for (var i = 0; i < order.length && !core; i++) core = attempt(order[i], spec.sealed, spec.band, rng);

    if (!core) {
      // Belt and braces. 7/4 with a tap has a reachable target at every value
      // from 1 to 7, so this fallback can never itself fail.
      core = attempt([7, 4], false, [4, 9], rng) || attempt([5, 3], false, [3, 8], rng);
    }

    var par = core.optimal + Math.max(2, 6 - t);
    var moveLimit = Math.max(core.optimal + 8, Math.round(core.optimal * 2.2) + t);

    return {
      tier: t,
      content: C,
      caps: core.caps,
      sealed: core.sealed,
      target: core.target,
      optimal: core.optimal,
      par: par,
      moveLimit: moveLimit,
      levels: core.startArr.slice(),
      startArr: core.startArr.slice(),
      _space: core.space,
      _distToGoal: core.distToGoal,
      moves: 0,
      wasted: 0,
      undosLeft: Math.max(1, 4 - t),
      history: [],          // [{ levels, moves, wasted, label }] for undo
      log: [],              // human-readable move list
      solved: false
    };
  }

  /* ------------------------------------------------------------ mechanics -- */

  function applyMove(p, mv) {
    var a = p.levels;
    if (mv.kind === 'fill') { a[mv.i] = p.caps[mv.i]; return; }
    if (mv.kind === 'empty') { p.wasted += a[mv.i]; a[mv.i] = 0; return; }
    var amt = Math.min(a[mv.i], p.caps[mv.j] - a[mv.j]);
    a[mv.i] -= amt; a[mv.j] += amt;
    mv.amt = amt;
  }

  function hitTarget(p) {
    for (var i = 0; i < p.levels.length; i++) if (p.levels[i] === p.target) return true;
    return false;
  }

  function bestMove(p) {
    var code = p._space.encode(p.levels);
    var here = p._distToGoal[code];
    if (here === undefined || here === 0) return null;
    var e = p._space.edges(code);
    for (var i = 0; i < e.length; i++) {
      if (p._distToGoal[e[i].to] === here - 1) return e[i].move;
    }
    return null;
  }

  /** The full optimal line from the current position, as a move array. */
  function optimalLine(p) {
    var space = p._space;
    var levels = p.levels.slice();
    var out = [];
    for (var guard = 0; guard < 80; guard++) {
      var code = space.encode(levels);
      var here = p._distToGoal[code];
      if (here === undefined || here === 0) break;
      var e = space.edges(code), step = null;
      for (var i = 0; i < e.length; i++) {
        if (p._distToGoal[e[i].to] === here - 1) { step = e[i]; break; }
      }
      if (!step) break;
      out.push(step.move);
      levels = space.decode(step.to);
    }
    return out;
  }

  function moveLabel(p, mv) {
    var C = p.content;
    var L = LETTERS;
    if (mv.kind === 'fill') return C.fillVerb + ' ' + L[mv.i];
    if (mv.kind === 'empty') return C.emptyVerb + ' ' + L[mv.i];
    return L[mv.i] + ' \u2192 ' + L[mv.j] + (mv.amt ? ' (' + mv.amt + ')' : '');
  }

  /* ================================================================ CSS == */

  var CSS = [
    '.pz-measure{display:grid;grid-template-columns:minmax(0,1fr) minmax(228px,286px);gap:18px;align-items:start}',
    '@media (max-width:860px){.pz-measure{grid-template-columns:1fr}}',
    '.pz-measure.is-panel{display:flex;flex-direction:column;gap:12px}',
    '.pz-measure-stage{display:flex;flex-direction:column;gap:14px}',

    '.pz-measure-bench{display:flex;gap:16px;justify-content:center;align-items:flex-end;flex-wrap:wrap;',
    '  padding:20px 16px 16px;border-radius:12px;border:1px solid var(--line);',
    '  background:radial-gradient(120% 90% at 50% 0%,rgba(255,255,255,.035),transparent 70%),#0a0d13}',
    '.pz-measure.is-panel .pz-measure-bench{gap:10px;padding:14px 8px 10px}',

    '.pz-measure-vessel{display:flex;flex-direction:column;align-items:center;gap:8px;padding:9px 10px 11px;',
    '  border-radius:11px;border:1px solid transparent;transition:border-color .2s var(--ease),',
    '  background .2s var(--ease),transform .2s var(--ease)}',
    '.pz-measure-vessel.is-src{border-color:var(--acc);background:var(--acc-wash);transform:translateY(-3px)}',
    '.pz-measure-vessel.is-hit .pz-measure-tube{box-shadow:0 0 0 2px var(--good),0 0 26px rgba(95,207,141,.4)}',

    '.pz-measure-head{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--text-2)}',
    '.pz-measure-head b{font-family:var(--font-mono);color:var(--acc-2);font-weight:700}',

    '.pz-measure-tube{position:relative;width:62px;border-radius:5px 5px 9px 9px;overflow:hidden;',
    '  background:linear-gradient(180deg,#0c1017,#12171f);border:1px solid #2b3442;',
    '  box-shadow:inset 0 0 18px rgba(0,0,0,.85);transition:box-shadow .3s var(--ease)}',
    '.pz-measure-fluid{position:absolute;left:0;right:0;bottom:0;height:0;',
    '  background:linear-gradient(180deg,color-mix(in srgb,var(--acc) 76%,#fff 6%),color-mix(in srgb,var(--acc) 44%,#000 30%));',
    '  box-shadow:0 -1px 0 rgba(255,255,255,.35) inset;transition:height .42s var(--ease)}',
    '.pz-measure-fluid::after{content:"";position:absolute;left:0;right:0;top:0;height:3px;',
    '  background:rgba(255,255,255,.5);opacity:.7}',
    '.pz-measure-tick{position:absolute;left:0;width:9px;height:1px;background:#39445a}',
    '.pz-measure-tick.is-five{width:16px;background:#55617c}',
    '.pz-measure-goal{position:absolute;left:0;right:0;height:0;border-top:2px dashed var(--good);',
    '  box-shadow:0 0 10px rgba(95,207,141,.45)}',
    '.pz-measure-goal span{position:absolute;right:2px;top:-13px;font-family:var(--font-mono);',
    '  font-size:9px;color:var(--good)}',
    '.pz-measure-cap{position:absolute;top:3px;right:4px;font-family:var(--font-mono);font-size:9px;color:var(--dimmer)}',

    '.pz-measure-amt{font-family:var(--font-mono);font-size:15px;color:var(--text);font-variant-numeric:tabular-nums}',
    '.pz-measure-amt small{color:var(--dimmer);font-size:10px;margin-left:2px}',

    '.pz-measure-acts{display:flex;gap:5px}',
    '.pz-measure-acts button{border-radius:7px;border:1px solid var(--line);font-size:10.5px;padding:4px 8px;',
    '  background:linear-gradient(180deg,var(--panel-3),var(--panel-2));color:var(--text-2);cursor:pointer;',
    '  font-family:var(--font-ui)}',
    '.pz-measure-acts button:hover:not(:disabled){border-color:var(--acc);color:var(--text)}',
    '.pz-measure-acts button:disabled{opacity:.25;cursor:default}',
    '.pz-measure-hand{font-family:var(--font-mono);font-size:10px;color:var(--acc-2);min-height:12px}',

    '.pz-measure-src{display:flex;align-items:center;gap:8px;justify-content:center;font-size:12px;',
    '  color:var(--dim);padding-top:2px}',
    '.pz-measure-src b{color:var(--text-2);font-weight:600}',

    '.pz-measure-rows{display:flex;flex-direction:column;gap:6px}',
    '.pz-measure-row{display:flex;justify-content:space-between;font-family:var(--font-mono);font-size:11px;color:var(--dim)}',
    '.pz-measure-row b{color:var(--acc-2)}',
    '.pz-measure-row.is-tight b{color:var(--bad)}',

    '.pz-measure-log{display:flex;flex-wrap:wrap;gap:4px}',
    '.pz-measure-log span{font-family:var(--font-mono);font-size:10px;padding:2px 6px;border-radius:5px;',
    '  background:var(--panel-2);border:1px solid var(--line-soft);color:var(--dim)}',
    '.pz-measure-log span.is-last{border-color:var(--acc);color:var(--acc-2)}',
    '.pz-measure-log .pz-measure-empty{border:none;background:none;font-style:italic;color:var(--dimmer)}',

    '.pz-measure-warn{font-size:12px;line-height:1.5;color:var(--warn);padding:9px 11px;border-radius:7px;',
    '  background:rgba(230,180,85,.08);border:1px solid rgba(230,180,85,.26)}',
    '.pz-measure-warn.is-bad{color:var(--bad);background:rgba(226,105,95,.08);border-color:rgba(226,105,95,.28)}'
  ].join('\n');

  /* ================================================================ ROOM == */
  /* The vessels are objects on the floor. You carry one to the tap, to the
     drain, or to another vessel — every BFS move is a walk with something
     heavy in your hands.
       #  wall   .  floor   1-3 vessels   T tap   X drain   S bench   @ start */

  var ROOM = [
    '###############',
    '#.....T.......#',
    '#.............#',
    '#...1.....2...#',
    '#.............#',
    '#.X...@......S#',
    '#.............#',
    '#......3......#',
    '###############'
  ];

  function readRoom(rows) {
    var tiles = [], spots = {}, y, x, ch;
    for (y = 0; y < rows.length; y++) {
      var line = [];
      for (x = 0; x < rows[y].length; x++) {
        ch = rows[y].charAt(x);
        line.push(ch === '#' ? 1 : 0);
        if (ch !== '#' && ch !== '.') spots[ch] = { x: x, y: y };
      }
      tiles.push(line);
    }
    return { w: rows[0].length, h: rows.length, tiles: tiles, spots: spots };
  }

  /* ================================================================ MOUNT = */

  var teardownFns = [];

  function mount(el, state, api, puzzle, skin) {
    var h = PS.ui.h;
    var C = puzzle.content;
    var n = puzzle.caps.length;
    var maxCap = Math.max.apply(null, puzzle.caps);
    var finished = false;
    var carry = -1;               // index of the vessel in your hands, or -1
    var arena = null;

    var vessels = [];             // [{ root, fluid, amt }]
    var handles = [];             // arena prop handles, one per vessel
    var chips = [];
    var cMoves = null;

    var stage = h('div', { class: 'pz-measure-stage' });
    var mapHost = h('div', {});
    var endBox = h('div', {});
    var bench = h('div', { class: 'pz-measure-bench' });
    var rows = h('div', { class: 'pz-measure-rows' });
    var logBox = h('div', { class: 'pz-measure-log' });
    var warnBox = h('div', {});
    var controls = h('div', { class: 'pz-col' });
    var panelRoot = h('div', { class: 'pz-measure' });
    var handLine = h('div', { class: 'pz-measure-hand' });

    /* ------------------------------------------------------------ vessels -- */
    /* The tubes are the readout now: they show every level and the target line
       at a glance. The doing happens in the room.                            */

    function buildVessel(i) {
      var cap = puzzle.caps[i];
      var tubeH = 62 + Math.round((cap / maxCap) * 74);

      var fluid = h('div', { class: 'pz-measure-fluid' });
      var tube = h('div', { class: 'pz-measure-tube', style: { height: tubeH + 'px' } }, [
        fluid,
        h('div', { class: 'pz-measure-cap', text: cap })
      ]);

      // A tick for every unit while that stays readable, otherwise every other.
      var step = cap <= 13 ? 1 : 2;
      for (var v = step; v < cap; v += step) {
        tube.appendChild(h('div', {
          class: 'pz-measure-tick' + (v % 5 === 0 ? ' is-five' : ''),
          style: { bottom: ((v / cap) * 100) + '%' }
        }));
      }
      if (puzzle.target <= cap) {
        tube.appendChild(h('div', {
          class: 'pz-measure-goal',
          style: { bottom: ((puzzle.target / cap) * 100) + '%' }
        }, [h('span', { text: puzzle.target })]));
      }

      var amt = h('div', { class: 'pz-measure-amt' }, [
        h('span', { text: '0' }), h('small', { text: C.unit })
      ]);

      var rootEl = h('div', { class: 'pz-measure-vessel' }, [
        h('div', { class: 'pz-measure-head' }, [
          h('span', { text: C.icons[i] || '\uD83E\uDDF4' }),
          h('b', { text: LETTERS[i] }),
          h('span', { text: C.vessels[i] || 'Vessel' })
        ]),
        tube, amt
      ]);

      vessels.push({ root: rootEl, fluid: fluid, amt: amt.childNodes[0] });
      return rootEl;
    }

    for (var vi = 0; vi < n; vi++) bench.appendChild(buildVessel(vi));

    /* --------------------------------------------------------------- room -- */

    function buildRoom() {
      if (!PS.arena || typeof PS.arena.create !== 'function') return false;

      var room = readRoom(ROOM);
      var spawn = room.spots['@'] || { x: 1, y: 1 };

      arena = PS.arena.create(mapHost, {
        map: { w: room.w, h: room.h, tiles: room.tiles },
        spawn: spawn,
        avatar: '\uD83E\uDDCD',
        light: state.stats.light,
        lightCurve: function (v) { return 4.8 + Math.min(100, Math.max(0, v)) / 100 * 2.6; },
        darkness: 0.5,
        memory: 0.72,
        compact: true
      });
      if (!arena) return false;
      teardownFns.push(function () { if (arena) { arena.destroy(); arena = null; } });
      arena.revealAll();

      arena.chip('Target', '\uD83C\uDFAF').set(puzzle.target + ' ' + C.unit);
      for (var i = 0; i < n; i++) {
        chips.push(arena.chip(LETTERS[i] + ' \u00B7 ' + (C.vessels[i] || 'Vessel'), C.icons[i] || '\uD83E\uDDF4'));
      }
      cMoves = arena.chip('Moves', '\uD83D\uDC63');

      for (i = 0; i < n; i++) {
        (function (idx) {
          var spot = room.spots[String(idx + 1)];
          if (!spot) return;
          handles.push(arena.prop({
            x: spot.x, y: spot.y, icon: C.icons[idx] || '\uD83E\uDDF4',
            label: LETTERS[idx], hint: 'walk onto it',
            // proximity, not step: a step prop only ever fires once, and this
            // is a thing you come back to again and again.
            trigger: 'proximity', radius: 0.8, once: false, emits: 0.8,
            onActivate: function () { touchVessel(idx); }
          }));
        })(i);
      }

      var tap = room.spots.T, drain = room.spots.X;
      if (tap) {
        arena.prop({
          x: tap.x, y: tap.y, icon: C.sourceIcon, label: C.source,
          hint: puzzle.sealed ? 'dry' : 'fill what you are carrying',
          trigger: 'proximity', radius: 0.8, once: false,
          emits: puzzle.sealed ? 0.35 : 1.1, botSkip: puzzle.sealed,
          onActivate: function () { atSource(); }
        });
      }
      if (drain) {
        arena.prop({
          x: drain.x, y: drain.y, icon: C.drainIcon || '\uD83D\uDD73\uFE0F', label: C.drain || 'the drain',
          hint: puzzle.sealed ? 'no use to you now' : 'tip it out here',
          trigger: 'proximity', radius: 0.8, once: false, emits: 0.3,
          glow: !puzzle.sealed, botSkip: true,
          onActivate: function () { atDrain(); }
        });
      }

      var seat = room.spots.S;
      if (seat) {
        arena.station({
          x: seat.x, y: seat.y, icon: '\uD83E\uDDEA', label: 'The bench',
          hint: 'read the levels', radius: 1.4, emits: 1.8,
          onEnter: function (panelEl) { PS.ui.append(panelEl, panelRoot); }
        });
      }

      arena.note(puzzle.sealed
        ? C.sealed + ' Walk onto a vessel to pick it up, then onto another to pour.'
        : 'Walk onto a vessel to pick it up. Carry it to ' + C.source + ' to fill it, to ' +
          (C.drain || 'the drain') + ' to tip it out, or onto another vessel to pour.');
      arena.button('\u21B6 Take it back', undo, 'pz-btn--sm');
      arena.button('\u270B Set it down', setDown, 'pz-btn--sm');
      arena.button('\u21A9 Guess it instead', walkAway, 'pz-btn--danger');
      return true;
    }

    /* ------------------------------------------------------------ actions -- */

    function setDown() {
      if (carry < 0 || finished) return;
      api.toast('You set ' + LETTERS[carry] + ' back down.', 'info', 1400);
      carry = -1;
      paint();
    }

    function touchVessel(i) {
      if (finished || puzzle.solved) return;
      if (carry < 0) {
        carry = i;
        api.toast('You pick up ' + LETTERS[i] + ' \u2014 ' + (C.vessels[i] || 'the vessel').toLowerCase() +
          ', ' + puzzle.levels[i] + ' ' + C.unit + ' in it.', 'info', 1800);
        paint();
        return;
      }
      if (carry === i) { setDown(); return; }
      if (puzzle.levels[carry] <= 0) { api.toast(LETTERS[carry] + ' is empty \u2014 nothing to pour.', 'bad'); return; }
      if (puzzle.levels[i] >= puzzle.caps[i]) { api.toast(LETTERS[i] + ' is already full.', 'bad'); return; }
      doMove({ kind: 'pour', i: carry, j: i });
    }

    function atSource() {
      if (finished || puzzle.solved) return;
      if (puzzle.sealed) { api.toast(C.sealed, 'bad', 3000); return; }
      if (carry < 0) { api.toast('You have nothing in your hands to fill.', 'bad'); return; }
      if (puzzle.levels[carry] >= puzzle.caps[carry]) { api.toast(LETTERS[carry] + ' is already full.', 'bad'); return; }
      doMove({ kind: 'fill', i: carry });
    }

    function atDrain() {
      if (finished || puzzle.solved) return;
      if (puzzle.sealed) { api.toast('Nothing is going down there tonight. Every drop stays in the set.', 'bad', 2600); return; }
      if (carry < 0) { api.toast('You have nothing in your hands to tip out.', 'bad'); return; }
      if (puzzle.levels[carry] <= 0) { api.toast(LETTERS[carry] + ' is already empty.', 'bad'); return; }
      doMove({ kind: 'empty', i: carry });
    }

    function doMove(mv) {
      if (finished || puzzle.solved) return;
      if (mv.kind === 'fill' && puzzle.levels[mv.i] >= puzzle.caps[mv.i]) return;
      if (mv.kind === 'empty' && puzzle.levels[mv.i] <= 0) return;
      if (mv.kind === 'pour' && (puzzle.levels[mv.i] <= 0 || puzzle.levels[mv.j] >= puzzle.caps[mv.j])) return;

      puzzle.history.push({ levels: puzzle.levels.slice(), wasted: puzzle.wasted, moves: puzzle.moves, carry: carry });
      applyMove(puzzle, mv);
      puzzle.moves++;
      puzzle.log.push(moveLabel(puzzle, mv));
      if (puzzle.log.length > 40) puzzle.log.shift();

      if (mv.kind === 'fill') api.toast(C.fillLine, 'info');
      else if (mv.kind === 'empty') api.toast(C.emptyLine, 'bad');
      else api.toast(C.pourLine, 'info', 1600);

      if (arena) {
        var p = arena.player();
        arena.dust(p.tx, p.ty, 8, mv.kind === 'empty' ? '#e2695f' : null);
      }

      if (hitTarget(puzzle)) { puzzle.solved = true; carry = -1; paint(); succeed(); return; }
      if (puzzle.moves >= puzzle.moveLimit) { paint(); ranOut(); return; }
      paint();
    }

    function undo() {
      if (finished || puzzle.solved) return;
      if (!puzzle.history.length) { api.toast('Nothing to take back.', 'bad'); return; }
      if (puzzle.undosLeft <= 0) { api.toast('You have run out of second thoughts.', 'bad'); return; }
      var prev = puzzle.history.pop();
      puzzle.levels = prev.levels;
      puzzle.wasted = prev.wasted;
      puzzle.moves = prev.moves;
      carry = prev.carry === undefined ? -1 : prev.carry;
      puzzle.undosLeft--;
      puzzle.log.pop();
      paint();
    }

    /* -------------------------------------------------------------- paint -- */

    function paint() {
      for (var i = 0; i < n; i++) {
        var v = vessels[i];
        var lvl = puzzle.levels[i];
        var cls = 'pz-measure-vessel';
        if (carry === i) cls += ' is-src';
        if (lvl === puzzle.target) cls += ' is-hit';
        v.root.className = cls;
        v.fluid.style.height = ((lvl / puzzle.caps[i]) * 100) + '%';
        v.amt.textContent = String(lvl);

        if (chips[i]) chips[i].set(lvl + ' / ' + puzzle.caps[i], lvl === puzzle.target ? 'warn' : null);
        if (handles[i]) {
          handles[i].setLabel(LETTERS[i] + ' \u00B7 ' + (C.vessels[i] || 'Vessel') + ' \u2014 ' +
            lvl + '/' + puzzle.caps[i] + ' ' + C.unit +
            (carry === i ? ' (in your hands)' : (carry >= 0 ? ' (pour ' + LETTERS[carry] + ' in)' : '')));
        }
      }

      if (arena) arena.setAvatar(carry >= 0 ? (C.icons[carry] || '\uD83E\uDDF4') : '\uD83E\uDDCD');
      if (cMoves) {
        var left = puzzle.moveLimit - puzzle.moves;
        cMoves.set(puzzle.moves + ' \u00B7 ' + left + ' left', left <= 4 ? 'bad' : null);
      }

      PS.ui.clear(handLine);
      PS.ui.append(handLine, [carry >= 0
        ? 'In your hands: ' + LETTERS[carry] + ' \u2014 ' + puzzle.levels[carry] + ' ' + C.unit
        : 'Both hands empty.']);

      paintRows();
      paintLog();
      paintWarn();
    }

    function row(k, v, tight) {
      return h('div', { class: 'pz-measure-row' + (tight ? ' is-tight' : '') }, [
        h('span', { text: k }), h('b', { text: v })
      ]);
    }

    function paintRows() {
      PS.ui.clear(rows);
      var left = puzzle.moveLimit - puzzle.moves;
      PS.ui.append(rows, [
        row('Target', puzzle.target + ' ' + C.unit),
        row('Moves made', String(puzzle.moves)),
        row('Par', puzzle.par + ' moves'),
        row('Best possible', puzzle.optimal + ' moves'),
        row('Moves left', String(left), left <= 4),
        row('Take-backs', String(puzzle.undosLeft)),
        row('Spilled', puzzle.wasted + ' ' + C.unit)
      ]);
    }

    function paintLog() {
      PS.ui.clear(logBox);
      if (!puzzle.log.length) {
        logBox.appendChild(h('span', { class: 'pz-measure-empty', text: 'Nothing poured yet.' }));
        return;
      }
      var tail = puzzle.log.slice(-9);
      for (var i = 0; i < tail.length; i++) {
        logBox.appendChild(h('span', { class: i === tail.length - 1 ? 'is-last' : '', text: tail[i] }));
      }
    }

    function paintWarn() {
      PS.ui.clear(warnBox);
      if (finished || puzzle.solved) return;
      var left = puzzle.moveLimit - puzzle.moves;
      if (left <= 3) {
        warnBox.appendChild(h('div', { class: 'pz-measure-warn is-bad', text:
          'You are nearly out of patience and out of ' + C.substance + '. ' + left + ' more moves and you are working with what you have.' }));
      } else if (carry >= 0) {
        warnBox.appendChild(h('div', { class: 'pz-measure-warn', text:
          LETTERS[carry] + ' is in your hands. Walk it onto another vessel to pour, or set it down.' }));
      } else if (puzzle.moves > puzzle.par) {
        warnBox.appendChild(h('div', { class: 'pz-measure-warn', text:
          'Past par. It is still solvable from here \u2014 it is always solvable from here \u2014 but it will not be pretty.' }));
      }
    }

    /* ------------------------------------------------------------ endings -- */

    function succeed() {
      var clean = puzzle.moves <= puzzle.par;
      if (arena) {
        arena.note(C.solve.replace('%T%', String(puzzle.target)));
        var p = arena.player();
        arena.ping(p.tx, p.ty, '#5fcf8d');
      }
      PS.ui.clear(endBox);
      PS.ui.append(endBox, [
        h('div', { class: 'pz-intro', text:
          C.solve.replace('%T%', String(puzzle.target)) + ' ' +
          (clean
            ? 'You did it in ' + puzzle.moves + ' moves against a best of ' + puzzle.optimal + '.'
            : 'It took you ' + puzzle.moves + ' moves; it could have been done in ' + puzzle.optimal + '.') }),
        h('div', { class: 'pz-choices' }, [
          choiceBtn(C.stay, 'scavenge'),
          choiceBtn(C.go, 'sprint')
        ])
      ]);
      api.flash();
    }

    function choiceBtn(spec, id) {
      return h('button', {
        class: 'pz-choice', type: 'button', 'data-act': 'choice:' + id,
        onclick: function () { finishRun(id); }
      }, [
        h('div', { class: 'pz-choice__i', text: spec.icon }),
        h('div', { class: 'pz-choice__t', text: spec.title }),
        h('div', { class: 'pz-choice__d', text: spec.desc })
      ]);
    }

    function finishRun(choice) {
      if (finished) return;
      finished = true;
      var clean = puzzle.moves <= puzzle.par;
      var tight = puzzle.moves <= puzzle.optimal + 1;
      var frugal = puzzle.wasted === 0;
      var stayed = choice === 'scavenge';
      var relief = C.relief || {};

      var tags = ['measured_it_out'];
      if (frugal) tags.push('wasted_nothing');
      if (tight) tags.push('worked_it_out_cold');

      api.finish({
        outcome: clean ? 'success' : 'partial',
        stats: {
          morale: clean ? 8 : 2,
          energy: (clean ? -4 : -7) - puzzle.tier + (relief.energy || 0) * (clean ? 1 : 0.5),
          health: (relief.health || 0) * (clean ? 1 : 0.5),
          light: (relief.light || 0) * (clean ? 1 : 0.5)
        },
        gain: stayed ? [C.item, C.bonus] : [C.item],
        lose: [],
        tags: tags.concat(stayed ? ['loaded_up'] : ['travelled_light']),
        signals: {
          logic: clean ? 3 : 2,
          caution: frugal ? 2 : 0,
          speed: tight ? 2 : 0,
          scavenge: stayed ? 2 : 0
        },
        choice: choice,
        summary: 'You got ' + puzzle.target + ' ' + C.unit + ' of ' + C.substance +
          ' out of vessels marked ' + puzzle.caps.join(' and ') + ', in ' + puzzle.moves + ' moves.'
      });
    }

    function ranOut() {
      if (finished) return;
      finished = true;
      paint();
      api.finish({
        outcome: 'fail',
        stats: { morale: -9, energy: -12, health: -2 },
        gain: [], lose: [],
        tags: ['lost_the_count'],
        signals: { logic: 0, caution: puzzle.wasted === 0 ? 1 : 0, brute: 1 },
        choice: null,
        summary: C.failLine
      });
    }

    function walkAway() {
      if (finished || puzzle.solved) return;
      finished = true;
      paint();
      api.finish({
        outcome: 'fail',
        stats: { morale: -6, energy: -5 },
        gain: [], lose: [],
        tags: ['left_it_unmeasured'],
        signals: { caution: 2, logic: 0 },
        choice: null,
        summary: 'You gave up on the arithmetic and took your chances without an exact measure.'
      });
    }

    /* ------------------------------------------------------------- layout -- */

    var sourceLine = puzzle.sealed
      ? h('div', { class: 'pz-measure-src' }, [h('span', { text: '\uD83D\uDEAB' }), h('b', { text: C.sealed })])
      : h('div', { class: 'pz-measure-src' }, [
          h('span', { text: C.sourceIcon }),
          'Unlimited from ', h('b', { text: C.source }), ' \u2014 the problem is not supply, it is the markings.'
        ]);

    PS.ui.append(panelRoot, [
      h('div', { class: 'pz-col' }, [
        h('div', { class: 'pz-intro', text: C.goal.replace('%T%', String(puzzle.target)) }),
        bench,
        handLine,
        sourceLine
      ]),
      h('div', { class: 'pz-col' }, [
        h('div', { class: 'pz-card' }, [h('div', { class: 'pz-card__head', text: 'Measure' }), rows]),
        warnBox,
        h('div', { class: 'pz-card' }, [h('div', { class: 'pz-card__head', text: 'What you did' }), logBox]),
        h('div', { class: 'pz-card' }, [h('div', { class: 'pz-card__head', text: 'Bench' }), controls])
      ])
    ]);

    PS.ui.append(stage, [mapHost, endBox]);
    PS.ui.append(el, stage);

    if (buildRoom()) {
      panelRoot.className = 'pz-measure is-panel';
      PS.ui.append(controls, h('div', { class: 'pz-note', text:
        'The vessels are on the floor of the room, not on this bench. Walk onto one to pick it up.' }));
    } else {
      // No arena layer: fall back to buttons on the bench so the scene is
      // always finishable.
      for (var q = 0; q < n; q++) {
        (function (idx) {
          var acts = h('div', { class: 'pz-measure-acts' }, [
            h('button', { type: 'button', onclick: function () { touchVessel(idx); } }, ['Take / pour']),
            puzzle.sealed ? null : h('button', { type: 'button', onclick: function () { carry = idx; atSource(); } }, [C.fillVerb]),
            puzzle.sealed ? null : h('button', { type: 'button', onclick: function () { carry = idx; atDrain(); } }, [C.emptyVerb])
          ]);
          vessels[idx].root.appendChild(acts);
        })(q);
      }
      PS.ui.append(controls, [
        h('div', { class: 'pz-row' }, [
          h('button', { class: 'pz-btn pz-btn--sm', type: 'button', 'data-act': 'undo', onclick: undo }, ['\u21B6 Take it back']),
          h('button', { class: 'pz-btn pz-btn--danger pz-btn--sm', type: 'button', 'data-act': 'walk', onclick: walkAway }, ['\u21A9 Guess it instead'])
        ])
      ]);
      PS.ui.append(mapHost, panelRoot);
    }

    paint();
    if (arena) arena.focus();
  }
  function unmount() {
    while (teardownFns.length) {
      try { teardownFns.pop()(); } catch (e) { /* keep unwinding */ }
    }
  }

  /* ================================================================ HINT = */

  function hint(puzzle, state, skin) {
    var C = puzzle.content;
    if (puzzle.solved) return 'It is already sitting in front of you. Pick a road.';
    var mv = bestMove(puzzle);
    if (!mv) {
      return 'Nothing you do from here shortens it. Tip one out and start the sequence again.';
    }
    var left = optimalLine(puzzle).length;
    var what;
    if (mv.kind === 'fill') what = C.fillVerb.toLowerCase() + ' ' + LETTERS[mv.i] + ' to the brim';
    else if (mv.kind === 'empty') what = C.emptyVerb.toLowerCase() + ' ' + LETTERS[mv.i] + ' completely';
    else what = 'pour ' + LETTERS[mv.i] + ' into ' + LETTERS[mv.j];
    return 'From here it is ' + left + ' move' + (left === 1 ? '' : 's') + ' if you do not waste one. Next: ' + what + '.';
  }

  /* ============================================================ AUTOSOLVE = */
  /* Headless. Walks the stored optimal line, so the bot's move count is the
     BFS optimum and its report is honest. */

  function autoSolve(puzzle, rng, state, tier, skin) {
    var line = optimalLine(puzzle);
    var moves = puzzle.moves + line.length;
    var stayed = rng.chance(0.45);
    var C = puzzle.content;
    var relief = C.relief || {};

    return {
      outcome: 'success',
      stats: {
        morale: 8,
        energy: -4 - puzzle.tier + (relief.energy || 0),
        health: relief.health || 0,
        light: relief.light || 0
      },
      gain: stayed ? [C.item, C.bonus] : [C.item],
      lose: [],
      tags: ['measured_it_out', 'wasted_nothing'],
      signals: { logic: 3, caution: 2, speed: 2, scavenge: stayed ? 2 : 0 },
      choice: stayed ? 'scavenge' : 'sprint',
      summary: 'Measured out ' + puzzle.target + ' ' + C.unit + ' in ' + moves + ' moves, which is the shortest there is.',
      moves: line.map(function (m) { return moveLabel(puzzle, m); })
    };
  }

  /* ============================================================ REGISTER = */

  PS.registry.register({
    id: 'measuring',
    name: 'Measuring',
    icon: '\uD83E\uDEA3',
    blurb: 'Get an exact volume out of vessels that are marked for anything but.',

    favors:   { logic: 3 },
    provides: ['supplies', 'food', 'medical'],
    tagHooks: ['has_rations', 'wasted_nothing'],
    requires: function (state) { return state.stats.morale > 8; },

    css: CSS,

    skins: [
      {
        id: 'fuel_mix', biome: 'industrial', title: 'Fuel Mixing', icon: '\u26FD', palette: 'rust',
        intro: 'The standby generator will take a charge and nothing else will get the pumps up. The cans on the rack are stamped with capacities that somebody chose to spite you. There is a bowser outside and a drain in the floor, and that is the whole of your equipment.',
        nouns: { substance: 'fuel mix', source: 'the bowser', vessel: 'jerrycan' }
      },
      {
        id: 'antidote', biome: 'shelter', title: 'Antidote Dilution', icon: '\uD83E\uDDEA', palette: 'bone',
        intro: 'The card taped to the cabinet gives a dose in millilitres and underlines it twice. Every graduated cylinder in the room is smashed; what is left is three unmarked vessels of known capacity. Somebody two rooms away is going to find out whether you can do this.',
        nouns: { substance: 'dilution', source: 'the saline drum', vessel: 'flask' }
      },
      {
        id: 'ration', biome: 'wilderness', title: 'Water Ration Split', icon: '\uD83E\uDEA3', palette: 'moss',
        intro: 'Four of you, one melt tank, and a day and a half to the road. Nobody is going to accept a share measured by eye, and they are right not to. The billy and the canteens hold what they hold.',
        nouns: { substance: 'water', source: 'the melt tank', vessel: 'canteen' }
      }
    ],

    build: build,
    mount: mount,
    unmount: unmount,
    hint: hint,
    autoSolve: autoSolve
  });

})(typeof window !== 'undefined' ? window : this);
